### ISSUE TITLE
NoMethod Error for link_to

### ISSUE THREAD

**Issue by huertanix** [leapcode/amber#10]
Not sure which version of the various gems Amber needs I should test with, but this is my setup:

Ruby version: 2.1.2
Amber version: 0.3.11
HAML version: 4.0.7

When I run `amber rebuild` on a fresh git clone and amber install, I get this error:

     /Users/huertanix/Source/riseup_help/amber/layouts/_riseup_bar.html.haml:4:in `block in singleton class': undefined method `link_to' for #<Amber::Render::View:0x007f9a57303038> (NoMethodError)
	from /Users/huertanix/Source/riseup_help/amber/layouts/_riseup_bar.html.haml:-10:in `instance_eval'
	from /Users/huertanix/Source/riseup_help/amber/layouts/_riseup_bar.html.haml:-10:in `singleton class'
	from /Users/huertanix/Source/riseup_help/amber/layouts/_riseup_bar.html.haml:-12:in `__tilt_70150418480120'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/haml.rb:19:in `evaluate'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/template.rb:128:in `render_haml'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/template.rb:73:in `render_html'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/template.rb:55:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/view.rb:70:in `render'
	from /Users/huertanix/Source/riseup_help/amber/layouts/home.html.haml:15:in `block in singleton class'
	from /Users/huertanix/Source/riseup_help/amber/layouts/home.html.haml:-9:in `instance_eval'
	from /Users/huertanix/Source/riseup_help/amber/layouts/home.html.haml:-9:in `singleton class'
	from /Users/huertanix/Source/riseup_help/amber/layouts/home.html.haml:-11:in `__tilt_70150418480120'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/haml.rb:19:in `evaluate'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/layout.rb:46:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/render/view.rb:66:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:131:in `block (2 levels) in render_content_files'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `open'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:129:in `block in render_content_files'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `each'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:121:in `render_content_files'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/static_page/render.rb:35:in `render_to_file'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/site.rb:47:in `block in render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/site.rb:46:in `each'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/site.rb:46:in `render'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/cli.rb:48:in `block in rebuild'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/site.rb:72:in `with_destination'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/lib/amber/cli.rb:47:in `rebuild'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/bin/amber:81:in `main'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/gems/amber-0.3.11/bin/amber:84:in `<top (required)>'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/bin/amber:22:in `load'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/bin/amber:22:in `<main>'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/huertanix/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by elijh** [comment]
sorry about that, link_to was in the unreleased 0.3.12. I guess I should have bumped it to 0.4.

anyway, 0.3.12 it is now available via rubygems, and it should work.
